name: Deploy

on:
  push:
    branches:
      - master
      - feature/*
      - bugfix/*
      - develop
  pull_request:
    branches:
      - master

env:
  ALICE_TESTNET_ADDRESS: ${{ secrets.ALICE_TESTNET_ADDRESS }}
  ALICE_TESTNET_WALLET_ID: ${{ secrets.ALICE_TESTNET_WALLET_ID }}
  BOB_TESTNET_ADDRESS: ${{ secrets.BOB_TESTNET_ADDRESS }}
  BOB_TESTNET_WALLET_ID: ${{ secrets.BOB_TESTNET_WALLET_ID }}

jobs:
  cd:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "16.x"
    - run: npx lerna init
    - run: yarn
    - run: yarn test
