name: stats

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches:
    - feature/stats
  schedule:
  # Run everyday Sunday at 4:00 UTC
  - cron: "0 4 * * 0"

# A workflow to check all markdown links
jobs:
  update-stats:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-node@v1
      with:
        node-version: "18.x"
    - name: build
      run: |
          yarn regtest:up;
          yarn
          ./jest/docker/restore_sql.sh
          yarn stats:sync
          yarn stats:dump
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Apply stat changes